### ISSUE TITLE
Needs EVE Routing

### ISSUE THREAD

**Issue by skord** [pubkraal/Eden#5]
It would be helpful to have a utility for routing ships around space, including jump bridge support.

**Comment by pubkraal** [comment]
As far as I am concerned we can do this, but I'm giving it a low priority. The skill plan + queue thing and fitting is the core aspect of the application and I'm focusing on that.

There are a lot of things we need to consider to make this work though, so if anyone can contribute to how it would work, let us know, write a message here and I'll compile the requirements later.

**Comment by themayarose** [comment]
One important thing to consider is the app size if we do this. Currently, the DB is about 50 MB, but I'm not including the map related tables in our dump. Considering that we may be looking at about 250 MB more of images once we put all the type images from CCP, we could end up with an app with more than 500 MB, which I think would be unacceptable.

**Comment by pubkraal** [comment]
Alright, that in itself is good enough reason to give it the lowest priority. I'm moving it to "could have" later.
